function df_depth_1_dxi = df_depth_1_dxi(in1)
%DF_DEPTH_1_DXI
%    DF_DEPTH_1_DXI = DF_DEPTH_1_DXI(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    25-Jul-2017 19:34:36

X_1 = in1(9,:);
Y_1 = in1(10,:);
Z_1 = in1(11,:);
phi = in1(4,:);
psi = in1(6,:);
theta = in1(5,:);
x_2_norm = in1(7,:);
t2 = cos(phi);
t3 = cos(psi);
t4 = sin(phi);
t5 = sin(psi);
t6 = sin(theta);
t7 = cos(theta);
df_depth_1_dxi = [1.0,0.0,-x_2_norm,-X_1.*x_2_norm.*(t2.*t5-t3.*t4.*t6)+Y_1.*x_2_norm.*(t2.*t3+t4.*t5.*t6)+Z_1.*t4.*t7.*x_2_norm,-Z_1.*(t7-t2.*t6.*x_2_norm)-X_1.*(t3.*t6+t2.*t3.*t7.*x_2_norm)-Y_1.*(t5.*t6+t2.*t5.*t7.*x_2_norm),-X_1.*(x_2_norm.*(t3.*t4-t2.*t5.*t6)+t5.*t7)-Y_1.*(x_2_norm.*(t4.*t5+t2.*t3.*t6)-t3.*t7)];
