function df_depth_2_dxi = df_depth_2_dxi(in1)
%DF_DEPTH_2_DXI
%    DF_DEPTH_2_DXI = DF_DEPTH_2_DXI(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    25-Jul-2017 19:34:36

X_1 = in1(9,:);
Y_1 = in1(10,:);
Z_1 = in1(11,:);
phi = in1(4,:);
psi = in1(6,:);
theta = in1(5,:);
y_2_norm = in1(8,:);
t2 = sin(psi);
t3 = sin(phi);
t4 = cos(phi);
t5 = cos(psi);
t6 = sin(theta);
t7 = cos(theta);
t8 = t4.*t5;
t9 = t2.*t4.*t6;
t10 = t2.*t3.*t6;
t11 = t2.*t4;
t12 = t2.*t3;
t13 = t4.*t5.*t6;
df_depth_2_dxi = [0.0,1.0,-y_2_norm,Z_1.*(t4.*t7+t3.*t7.*y_2_norm)+X_1.*(t12+t13-y_2_norm.*(t11-t3.*t5.*t6))+Y_1.*(t9+y_2_norm.*(t8+t10)-t3.*t5),X_1.*(t3.*t5.*t7-t4.*t5.*t7.*y_2_norm)+Y_1.*(t2.*t3.*t7-t2.*t4.*t7.*y_2_norm)-Z_1.*(t3.*t6-t4.*t6.*y_2_norm),-Y_1.*(t11+y_2_norm.*(t12+t13)-t3.*t5.*t6)-X_1.*(t8+t10-y_2_norm.*(t9-t3.*t5))];
