function df_depth_1_dt = df_depth_1_dt(in1)
%DF_DEPTH_1_DT
%    DF_DEPTH_1_DT = DF_DEPTH_1_DT(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    26-Jul-2017 13:55:12

x_2_norm = in1(7,:);
df_depth_1_dt = [1.0,0.0,-x_2_norm];
