function df_nodepth_dt = df_nodepth_dt(in1)
%DF_NODEPTH_DT
%    DF_NODEPTH_DT = DF_NODEPTH_DT(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    26-Jul-2017 13:55:12

phi = in1(4,:);
psi = in1(6,:);
theta = in1(5,:);
x_1_norm = in1(12,:);
x_2_norm = in1(7,:);
y_1_norm = in1(13,:);
y_2_norm = in1(8,:);
t2 = sin(phi);
t3 = sin(psi);
t4 = cos(phi);
t5 = cos(psi);
t6 = sin(theta);
t7 = cos(theta);
t8 = t2.*t3;
t9 = t4.*t5.*t6;
t10 = t8+t9;
t11 = t2.*t5;
t12 = t11-t3.*t4.*t6;
t13 = t3.*t4;
t14 = t4.*t5;
t15 = t2.*t3.*t6;
df_nodepth_dt = [-t2.*t7-y_1_norm.*(t14+t15+t12.*y_2_norm)+x_1_norm.*(t13+t10.*y_2_norm-t2.*t5.*t6)+t4.*t7.*y_2_norm,-t6+x_1_norm.*(t5.*t7-t10.*x_2_norm)+y_1_norm.*(t3.*t7+t12.*x_2_norm)-t4.*t7.*x_2_norm,y_1_norm.*(x_2_norm.*(t14+t15)-t3.*t7.*y_2_norm)+t6.*y_2_norm-x_1_norm.*(x_2_norm.*(t13-t2.*t5.*t6)+t5.*t7.*y_2_norm)+t2.*t7.*x_2_norm];
