function f_depth_1 = f_depth_1(in1)
%F_DEPTH_1
%    F_DEPTH_1 = F_DEPTH_1(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    26-Jul-2017 13:55:12

X_1 = in1(9,:);
Y_1 = in1(10,:);
Z_1 = in1(11,:);
phi = in1(4,:);
psi = in1(6,:);
theta = in1(5,:);
tx = in1(1,:);
tz = in1(3,:);
x_2_norm = in1(7,:);
t2 = cos(psi);
t3 = cos(theta);
t4 = sin(psi);
t5 = sin(phi);
t6 = cos(phi);
t7 = sin(theta);
f_depth_1 = tx-tz.*x_2_norm-Z_1.*(t7+t3.*t6.*x_2_norm)-X_1.*(x_2_norm.*(t4.*t5+t2.*t6.*t7)-t2.*t3)+Y_1.*(x_2_norm.*(t2.*t5-t4.*t6.*t7)+t3.*t4);
