function f_depth_2 = f_depth_2(in1)
%F_DEPTH_2
%    F_DEPTH_2 = F_DEPTH_2(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    26-Jul-2017 13:55:12

X_1 = in1(9,:);
Y_1 = in1(10,:);
Z_1 = in1(11,:);
phi = in1(4,:);
psi = in1(6,:);
theta = in1(5,:);
ty = in1(2,:);
tz = in1(3,:);
y_2_norm = in1(8,:);
t2 = sin(psi);
t3 = cos(phi);
t4 = cos(psi);
t5 = sin(phi);
t6 = sin(theta);
t7 = cos(theta);
f_depth_2 = ty+Z_1.*(t5.*t7-t3.*t7.*y_2_norm)-tz.*y_2_norm-X_1.*(y_2_norm.*(t2.*t5+t3.*t4.*t6)+t2.*t3-t4.*t5.*t6)+Y_1.*(y_2_norm.*(t4.*t5-t2.*t3.*t6)+t3.*t4+t2.*t5.*t6);
